import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowLeft, CheckCircle2, ChevronDown, FileText, Loader2, LockKeyhole, Paperclip, Send, X } from "lucide-react";
import { toast } from "sonner";

type FieldType = "text" | "textarea" | "email" | "phone" | "cpf" | "number" | "select" | "radio" | "checkbox" | "date" | "file";
type Field = { id: string; fieldKey: string; label: string; placeholder: string | null; helpText: string | null; fieldType: FieldType; isRequired: boolean; options: { label: string; value: string }[]; validationRules: Record<string, unknown> };
type TalentForm = { id: string; publicSlug: string; title: string; subtitle: string; bannerUrl: string | null; lgpdDisclaimer: string; successTitle: string; successMessage: string; fields: Field[] };
const fileTypes = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];

function maskPhone(value: string) { const digits = value.replace(/\D/g, "").slice(0, 11); return digits.length <= 10 ? digits.replace(/(\d{2})(\d)/, "($1) $2").replace(/(\d{4})(\d)/, "$1-$2") : digits.replace(/(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2"); }
function maskCpf(value: string) { return value.replace(/\D/g, "").slice(0, 11).replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2"); }

function FieldControl({ field, value, onChange, file, onFile }: { field: Field; value: unknown; onChange: (value: unknown) => void; file?: File; onFile: (file: File | undefined) => void }) {
  const base = "mt-2 w-full rounded-xl border border-zinc-700 bg-zinc-950/60 px-3.5 py-3 text-sm text-zinc-100 outline-none transition placeholder:text-zinc-600 focus:border-zinc-400 focus:ring-2 focus:ring-white/10";
  const fieldId = `talent-${field.id}`;
  const label = <label htmlFor={fieldId} className="text-sm font-medium text-zinc-100">{field.label}{field.isRequired && <span className="ml-1 text-emerald-300">*</span>}</label>;
  const hint = field.helpText && <p className="mt-1.5 text-xs leading-5 text-zinc-500">{field.helpText}</p>;
  if (field.fieldType === "textarea") return <div>{label}<textarea id={fieldId} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder ?? ""} rows={4} className={base} />{hint}</div>;
  if (field.fieldType === "select") return <div>{label}<div className="relative"><select id={fieldId} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} className={`${base} appearance-none pr-9`}><option value="">Selecione uma opção</option>{field.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-zinc-500" /></div>{hint}</div>;
  if (field.fieldType === "radio") return <div>{label}<div className="mt-3 grid gap-2">{field.options.map((option) => <label key={option.value} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3.5 py-3 text-sm transition ${value === option.value ? "border-zinc-300 bg-white/10 text-white" : "border-zinc-800 text-zinc-400 hover:border-zinc-600"}`}><input className="accent-white" checked={value === option.value} onChange={() => onChange(option.value)} type="radio" name={field.fieldKey} />{option.label}</label>)}</div>{hint}</div>;
  if (field.fieldType === "checkbox") { const selected = Array.isArray(value) ? value : []; return <div>{label}<div className="mt-3 grid gap-2">{field.options.map((option) => <label key={option.value} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3.5 py-3 text-sm transition ${selected.includes(option.value) ? "border-zinc-300 bg-white/10 text-white" : "border-zinc-800 text-zinc-400 hover:border-zinc-600"}`}><input className="accent-white" checked={selected.includes(option.value)} onChange={() => onChange(selected.includes(option.value) ? selected.filter((item) => item !== option.value) : [...selected, option.value])} type="checkbox" />{option.label}</label>)}</div>{hint}</div>; }
  if (field.fieldType === "file") return <div>{label}<label htmlFor={fieldId} className="mt-2 flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-zinc-700 bg-zinc-950/50 px-4 py-4 transition hover:border-zinc-400 hover:bg-white/[0.04]"><span className="flex size-9 items-center justify-center rounded-lg bg-white/10 text-zinc-200"><Paperclip className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm font-medium text-zinc-100">{file?.name ?? "Anexe o seu currículo"}</strong><span className="mt-0.5 block text-xs text-zinc-500">PDF ou DOCX · até 5 MB</span></span>{file && <button onClick={(event) => { event.preventDefault(); onFile(undefined); }} className="rounded-lg p-1.5 text-zinc-400 hover:bg-white/10 hover:text-white"><X className="size-4" /></button>}<input id={fieldId} type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="sr-only" onChange={(event) => onFile(event.target.files?.[0])} /></label>{hint}</div>;
  const type = field.fieldType === "email" ? "email" : field.fieldType === "number" ? "number" : field.fieldType === "date" ? "date" : "text";
  const display = field.fieldType === "phone" ? maskPhone(String(value ?? "")) : field.fieldType === "cpf" ? maskCpf(String(value ?? "")) : String(value ?? "");
  return <div>{label}<input id={fieldId} type={type} value={display} onChange={(event) => onChange(field.fieldType === "phone" ? maskPhone(event.target.value) : field.fieldType === "cpf" ? maskCpf(event.target.value) : event.target.value)} placeholder={field.placeholder ?? ""} className={base} />{hint}</div>;
}

export default function TalentPublicForm() {
  const [, params] = useRoute("/trabalhe-conosco/:slug");
  const [, setLocation] = useLocation();
  const slug = params?.slug ?? "";
  const [form, setForm] = useState<TalentForm | null>(null);
  const [answers, setAnswers] = useState<Record<string, unknown>>({});
  const [files, setFiles] = useState<Record<string, File | undefined>>({});
  const [accepted, setAccepted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const required = useMemo(() => form?.fields.filter((field) => field.isRequired) ?? [], [form]);
  useEffect(() => { document.title = "Trabalhe Conosco — Vida Card"; setLoading(true); fetch(`/api/talent/public/${encodeURIComponent(slug)}`).then(async (response) => ({ response, body: await response.json().catch(() => ({})) })).then(({ response, body }) => { if (!response.ok) { toast.error(body.error ?? "Página não encontrada"); setForm(null); return; } setForm(body); }).catch(() => toast.error("Não foi possível carregar esta oportunidade")).finally(() => setLoading(false)); }, [slug]);
  const setAnswer = (key: string, value: unknown) => setAnswers((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!form) return;
    const missing = required.find((field) => { const value = answers[field.fieldKey]; return field.fieldType === "file" ? !files[field.fieldKey] : !value || (Array.isArray(value) && !value.length); });
    if (missing) { toast.error(`Preencha o campo obrigatório: ${missing.label}`); return; }
    if (!accepted) { toast.error("É necessário aceitar o termo de privacidade para enviar sua candidatura"); return; }
    for (const file of Object.values(files)) if (file && (!fileTypes.includes(file.type) || file.size > 5 * 1024 * 1024)) { toast.error("Os anexos devem ser PDF ou DOCX de até 5 MB"); return; }
    setSending(true); try { const body = new FormData(); body.set("answers", JSON.stringify(answers)); body.set("lgpdAccepted", "true"); Object.entries(files).forEach(([key, file]) => { if (file) body.append(`file_${key}`, file); }); const response = await fetch(`/api/talent/public/${encodeURIComponent(slug)}/submit`, { method: "POST", body }); const result = await response.json().catch(() => ({})); if (!response.ok) { toast.error(result.error ?? "Não foi possível enviar a candidatura"); return; } setSent(true); window.scrollTo({ top: 0, behavior: "smooth" }); } catch { toast.error("Não foi possível enviar sua candidatura"); } finally { setSending(false); }
  }
  if (loading) return <main className="min-h-screen bg-zinc-950 px-5 py-20 text-white"><div className="mx-auto max-w-2xl animate-pulse"><div className="h-6 w-40 rounded bg-white/10" /><div className="mt-10 h-10 w-2/3 rounded bg-white/10" /><div className="mt-4 h-5 w-full rounded bg-white/[0.06]" /><div className="mt-12 space-y-6">{[1, 2, 3, 4].map((item) => <div key={item} className="h-16 rounded-xl bg-white/[0.05]" />)}</div></div></main>;
  if (!form) return <main className="grid min-h-screen place-items-center bg-zinc-950 px-6 text-center text-white"><div><FileText className="mx-auto size-11 text-zinc-600" /><h1 className="mt-5 font-display text-2xl font-semibold">Página não encontrada</h1><p className="mt-2 max-w-sm text-sm text-zinc-400">Esta oportunidade não está disponível ou ainda não foi publicada.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2.5 text-sm hover:bg-white/10"><ArrowLeft className="size-4" />Voltar ao início</Link></div></main>;
  if (sent) return <main className="grid min-h-screen place-items-center bg-zinc-950 px-6 text-center text-white"><div className="max-w-xl"><span className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-emerald-400/10 text-emerald-300"><CheckCircle2 className="size-8" /></span><p className="mt-8 text-xs font-medium uppercase tracking-[0.18em] text-zinc-500">Vida Card · Banco de Talentos</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight">{form.successTitle}</h1><p className="mt-4 text-base leading-7 text-zinc-400">{form.successMessage}</p><button onClick={() => setLocation("/")} className="mt-8 rounded-xl border border-white/15 px-4 py-2.5 text-sm hover:bg-white/10">Voltar ao início</button></div></main>;
  return <main className="min-h-screen bg-zinc-950 text-white"><div className="fixed inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-zinc-500 to-transparent" /><header className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><Link href="/" className="font-display text-sm font-semibold tracking-[0.16em] text-zinc-100">TRÁFEGO <span className="text-zinc-500">PRO</span></Link><span className="rounded-full border border-white/10 px-3 py-1.5 text-[11px] font-medium text-zinc-400">Vida Card · Banco de Talentos</span></header><section className="mx-auto max-w-5xl px-5 pb-16 pt-10 md:pb-24 md:pt-16"><div className="grid gap-12 lg:grid-cols-[minmax(0,0.85fr)_minmax(480px,1.15fr)]"><aside className="lg:sticky lg:top-14 lg:self-start"><p className="text-xs font-medium uppercase tracking-[0.18em] text-emerald-300">Oportunidades</p><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight md:text-5xl">{form.title}</h1><p className="mt-5 max-w-md text-base leading-7 text-zinc-400">{form.subtitle}</p><div className="mt-10 flex gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><LockKeyhole className="mt-0.5 size-4 shrink-0 text-zinc-300" /><p className="text-xs leading-5 text-zinc-500">Suas informações são tratadas de forma segura e usadas exclusivamente no processo de recrutamento e seleção.</p></div></aside><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20 sm:p-8"><div className="mb-8 border-b border-white/10 pb-6"><h2 className="font-display text-xl font-semibold">Envie a sua candidatura</h2><p className="mt-1.5 text-sm text-zinc-500">Campos com <span className="text-emerald-300">*</span> são obrigatórios.</p></div><div className="space-y-6">{form.fields.map((field) => <FieldControl key={field.id} field={field} value={answers[field.fieldKey]} onChange={(value) => setAnswer(field.fieldKey, value)} file={files[field.fieldKey]} onFile={(file) => setFiles((current) => ({ ...current, [field.fieldKey]: file }))} />)}</div><label className="mt-8 flex cursor-pointer items-start gap-3 rounded-xl border border-white/10 bg-black/20 p-4 text-xs leading-5 text-zinc-400"><input checked={accepted} onChange={(event) => setAccepted(event.target.checked)} type="checkbox" className="mt-0.5 size-4 accent-white" /><span>{form.lgpdDisclaimer}</span></label><button disabled={sending} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-semibold text-zinc-950 transition hover:bg-zinc-200 disabled:cursor-not-allowed disabled:opacity-60">{sending ? <><Loader2 className="size-4 animate-spin" />Enviando candidatura...</> : <><Send className="size-4" />Enviar candidatura</>}</button></form></div></section></main>;
}
