-- Aplicado em 2026-09-24 no Supabase "trafegopro-analise" (migração site_tables_from_manus_mysql).
-- Tabelas que no Manus viviam no MySQL da plataforma. Acesso apenas pelo servidor (service_role):
-- RLS ligado sem políticas e sem permissões para anon/authenticated.

create table if not exists public.feedback_leads (
  id bigint generated by default as identity primary key,
  unit text not null,
  responsible text not null,
  week_start date not null,
  week_end date not null,
  total_leads integer not null default 0,
  leads_contacted integer not null default 0,
  leads_responded integer not null default 0,
  leads_converted integer not null default 0,
  leads_lost integer not null default 0,
  leads_in_negotiation integer not null default 0,
  main_reason text,
  loss_reason text not null default '',
  lead_quality integer not null default 0,
  creative_feedback text,
  general_observations text,
  observations text,
  agency_satisfaction integer not null default 0,
  communication_clarity text not null default '',
  agency_adjustment text,
  support_needed text,
  submitted_at timestamptz not null default now(),
  submitted_by_user_id text,
  submitted_by_email text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists idx_feedback_leads_unit_week on public.feedback_leads (unit, week_start desc);

create table if not exists public.form_api_keys (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  key_prefix text not null,
  key_hash text not null unique,
  client_ids jsonb not null default '[]'::jsonb,
  allowed_origins jsonb,
  created_by text not null,
  expires_at timestamptz,
  revoked_at timestamptz,
  rate_window_started_at timestamptz,
  rate_window_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.form_submissions (
  id text primary key default gen_random_uuid()::text,
  form_key_id text not null references public.form_api_keys(id),
  form_name text not null,
  client_id text not null,
  fields jsonb not null default '{}'::jsonb,
  metadata jsonb,
  ip_hash text,
  submitted_at timestamptz not null default now()
);
create index if not exists idx_form_submissions_client_date on public.form_submissions (client_id, submitted_at desc);
create index if not exists idx_form_submissions_key_date on public.form_submissions (form_key_id, submitted_at desc);

create table if not exists public.external_ai_api_tokens (
  id text primary key default gen_random_uuid()::text,
  owner_user_id text not null,
  name text not null,
  token_prefix text not null,
  token_hash text not null unique,
  scopes_json jsonb not null default '[]'::jsonb,
  unit_ids_json jsonb not null default '[]'::jsonb,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_used_at timestamptz,
  rate_window_started_at timestamptz,
  rate_window_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_external_ai_tokens_owner on public.external_ai_api_tokens (owner_user_id, created_at desc);

create table if not exists public.external_ai_api_audit_logs (
  id bigint generated by default as identity primary key,
  token_id text not null,
  request_method text not null,
  request_path text not null,
  http_status integer not null,
  outcome text not null,
  remote_ip_hash text,
  created_at timestamptz not null default now()
);
create index if not exists idx_external_ai_audit_token on public.external_ai_api_audit_logs (token_id, created_at desc);

create table if not exists public.social_meta_connections (
  id text primary key,
  owner_user_id text not null,
  unit_id text not null,
  unit_name text not null,
  facebook_page_id text not null,
  facebook_page_name text not null,
  instagram_account_id text,
  instagram_username text,
  access_token_encrypted text not null,
  token_expires_at timestamptz,
  granted_scopes text,
  connection_status text not null default 'active' check (connection_status in ('active','expired','revoked','error')),
  automation_enabled boolean not null default true,
  automation_paused_at timestamptz,
  automation_last_error text,
  last_error_code text,
  last_error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_user_id, facebook_page_id)
);

create table if not exists public.social_posts (
  id text primary key,
  client_batch_key text,
  owner_user_id text not null,
  unit_id text not null,
  unit_name text not null,
  social_connection_id text,
  title text not null,
  caption text not null,
  link_url text,
  content_format text not null check (content_format in ('image','carousel','video','reel')),
  target_facebook boolean not null default false,
  target_instagram boolean not null default false,
  status text not null default 'draft' check (status in ('draft','scheduled','publishing','published','partially_published','failed','cancelled','waiting_connection')),
  scheduled_for timestamptz,
  published_at timestamptz,
  facebook_post_id text,
  instagram_media_id text,
  facebook_schedule_status text not null default 'not_requested' check (facebook_schedule_status in ('not_requested','pending','scheduled','failed')),
  instagram_schedule_status text not null default 'not_requested' check (instagram_schedule_status in ('not_requested','pending','publishing','published','retrying','failed')),
  instagram_attempt_count integer not null default 0,
  instagram_next_attempt_at timestamptz,
  facebook_schedule_error text,
  provider_state_encrypted text,
  created_by_user_id text not null,
  updated_by_user_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_user_id, client_batch_key)
);
create index if not exists idx_social_posts_schedule on public.social_posts (status, scheduled_for);
create index if not exists idx_social_posts_owner on public.social_posts (owner_user_id, scheduled_for);

create table if not exists public.social_post_media (
  id text primary key,
  post_id text not null references public.social_posts(id) on delete cascade,
  sort_order integer not null,
  storage_key text,
  public_url text not null,
  media_type text not null check (media_type in ('image','video')),
  alt_text text,
  created_at timestamptz not null default now(),
  unique (post_id, sort_order)
);

create table if not exists public.social_publication_attempts (
  id bigint generated by default as identity primary key,
  post_id text not null references public.social_posts(id) on delete cascade,
  channel text not null check (channel in ('facebook','instagram')),
  action text not null check (action in ('scheduled','published','failed','skipped')),
  provider_post_id text,
  provider_error_code text,
  safe_message text,
  occurred_at timestamptz not null default now()
);
create index if not exists idx_social_attempts_post on public.social_publication_attempts (post_id, occurred_at);

create table if not exists public.social_meta_oauth_sessions (
  id text primary key,
  owner_user_id text not null,
  candidates_encrypted text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.social_publishing_settings (
  id smallint primary key,
  schedule_cron_task_uid text,
  scheduler_status text not null default 'inactive' check (scheduler_status in ('inactive','active','paused')),
  updated_at timestamptz not null default now()
);
insert into public.social_publishing_settings (id, scheduler_status) values (1, 'inactive') on conflict (id) do nothing;

-- Janela de rate limit de 1 minuto, atômica.
create or replace function public.consume_form_api_key_rate(p_id text)
returns integer language sql security invoker set search_path = public as $$
  update public.form_api_keys set
    rate_window_count = case when rate_window_started_at is null or rate_window_started_at < now() - interval '1 minute' then 1 else rate_window_count + 1 end,
    rate_window_started_at = case when rate_window_started_at is null or rate_window_started_at < now() - interval '1 minute' then now() else rate_window_started_at end
  where id = p_id
  returning rate_window_count;
$$;

create or replace function public.consume_external_ai_token_rate(p_id text)
returns integer language sql security invoker set search_path = public as $$
  update public.external_ai_api_tokens set
    rate_window_count = case when rate_window_started_at is null or rate_window_started_at < now() - interval '1 minute' then 1 else rate_window_count + 1 end,
    rate_window_started_at = case when rate_window_started_at is null or rate_window_started_at < now() - interval '1 minute' then now() else rate_window_started_at end,
    last_used_at = now()
  where id = p_id
  returning rate_window_count;
$$;

-- Criação de publicação + mídias numa transação só.
create or replace function public.create_social_post_with_media(p_post jsonb, p_media jsonb)
returns void language plpgsql security invoker set search_path = public as $$
begin
  insert into public.social_posts (id, client_batch_key, owner_user_id, unit_id, unit_name, social_connection_id, title, caption, link_url, content_format, target_facebook, target_instagram, status, scheduled_for, created_by_user_id, updated_by_user_id)
  values (p_post->>'id', p_post->>'client_batch_key', p_post->>'owner_user_id', p_post->>'unit_id', p_post->>'unit_name', p_post->>'social_connection_id', p_post->>'title', p_post->>'caption', p_post->>'link_url', p_post->>'content_format', (p_post->>'target_facebook')::boolean, (p_post->>'target_instagram')::boolean, p_post->>'status', (p_post->>'scheduled_for')::timestamptz, p_post->>'owner_user_id', p_post->>'owner_user_id');
  insert into public.social_post_media (id, post_id, sort_order, public_url, media_type, alt_text)
  select gen_random_uuid()::text, p_post->>'id', (m.ord - 1)::int, m.item->>'url', m.item->>'media_type', nullif(m.item->>'alt_text', '')
  from jsonb_array_elements(coalesce(p_media, '[]'::jsonb)) with ordinality as m(item, ord);
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['feedback_leads','form_api_keys','form_submissions','external_ai_api_tokens','external_ai_api_audit_logs','social_meta_connections','social_posts','social_post_media','social_publication_attempts','social_meta_oauth_sessions','social_publishing_settings'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end $$;

revoke execute on function public.consume_form_api_key_rate(text) from public, anon, authenticated;
revoke execute on function public.consume_external_ai_token_rate(text) from public, anon, authenticated;
revoke execute on function public.create_social_post_with_media(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.consume_form_api_key_rate(text) to service_role;
grant execute on function public.consume_external_ai_token_rate(text) to service_role;
grant execute on function public.create_social_post_with_media(jsonb, jsonb) to service_role;

-- Bucket público das mídias de publicações (a Meta baixa pela URL).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('social-media', 'social-media', true, 52428800, array['image/jpeg','image/png','image/webp','video/mp4','video/quicktime'])
on conflict (id) do nothing;

-- Migração site_tables_legacy_columns: colunas legadas vindas do MySQL do Manus.
alter table public.feedback_leads
  add column if not exists leads_card integer,
  add column if not exists leads_consultation integer,
  add column if not exists leads_dentistry integer,
  add column if not exists leads_business_pj integer,
  add column if not exists leads_out_of_area integer,
  add column if not exists leads_answered integer,
  add column if not exists leads_no_answer integer,
  add column if not exists sales_closed integer;
alter table public.external_ai_api_tokens
  add column if not exists revoked_by_user_id text,
  add column if not exists updated_at timestamptz;
