import { Check, ChevronDown } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

export type TalentSelectOption = { value: string; label: string; description?: string };

export function TalentDashboardSelect({ value, options, onChange, placeholder = "Selecione uma opção", ariaLabel, className = "" }: { value: string; options: TalentSelectOption[]; onChange: (value: string) => void; placeholder?: string; ariaLabel: string; className?: string }) {
  const selected = options.find((option) => option.value === value);
  return <Popover><PopoverTrigger asChild><button type="button" aria-label={ariaLabel} className={`inline-flex min-h-10 w-full items-center gap-2 rounded-xl border border-white/10 bg-white/[0.035] px-3 py-2.5 text-left text-xs text-foreground shadow-sm transition-all duration-200 hover:border-zinc-500 hover:bg-white/[0.06] focus:outline-none focus:ring-1 focus:ring-zinc-400 ${className}`}><span className={`min-w-0 flex-1 truncate font-medium ${selected ? "text-foreground" : "text-muted-foreground"}`}>{selected?.label ?? placeholder}</span><ChevronDown className="size-4 shrink-0 text-muted-foreground" /></button></PopoverTrigger><PopoverContent align="start" className="w-[min(22rem,calc(100vw-2rem))] rounded-2xl border-border bg-[color:var(--color-surface)] p-2 text-foreground shadow-2xl"><div className="max-h-64 overflow-y-auto">{options.map((option) => { const active = option.value === value; return <button key={option.value} type="button" onClick={() => onChange(option.value)} className={`flex w-full items-center justify-between gap-3 rounded-xl px-3 py-3 text-left text-sm transition-colors ${active ? "bg-zinc-200 text-zinc-950 shadow-sm" : "text-foreground hover:bg-white/[0.06]"}`}><span className="min-w-0"><span className="block truncate font-medium">{option.label}</span>{option.description && <span className={`mt-0.5 block truncate text-xs ${active ? "text-zinc-700" : "text-muted-foreground"}`}>{option.description}</span>}</span>{active && <Check className="size-4 shrink-0" />}</button>; })}</div></PopoverContent></Popover>;
}
